import { useEffect } from 'react'
import { Capacitor } from '@capacitor/core'
import { CapacitorUpdater } from '@capgo/capacitor-updater'
import { API_URL } from '../lib/config'

/**
 * Self-hosted live updates for the native app (Android/iOS).
 *
 * The server publishes the current web bundle at `<API>/updates/latest.json`:
 *   { "version": "<git sha>", "path": "tv-<git sha>.zip", "checksum": "<sha256 of the zip>" }
 * (generated by deploy/Dockerfile.web and served by Caddy). On start, and every few hours,
 * the app compares that version with the one it is running; when they differ it downloads
 * the zip and switches to it, so UI changes reach every TV without reinstalling the APK.
 * Native changes (new plugins) still need a new APK; the plugin then resets to the built-in
 * bundle automatically (resetWhenUpdate).
 *
 * In a browser this hook does nothing.
 */

const BUILT_VERSION: string = import.meta.env.VITE_BUNDLE_VERSION || 'dev'
const CHECK_EVERY_MS = 6 * 60 * 60 * 1000

interface LatestManifest {
  version: string
  path: string
  /** SHA-256 (hex) of the zip; the plugin verifies it after downloading */
  checksum?: string
}

export function useLiveUpdate() {
  useEffect(() => {
    if (!Capacitor.isNativePlatform() || !Capacitor.isPluginAvailable('CapacitorUpdater')) return
    let cancelled = false

    // Tell the plugin this bundle booted fine; otherwise it rolls back to the previous one.
    CapacitorUpdater.notifyAppReady().catch(() => {})

    const check = async () => {
      try {
        const current = await CapacitorUpdater.current()
        const running =
          current.bundle.id === 'builtin' || current.bundle.version === 'builtin'
            ? BUILT_VERSION
            : current.bundle.version
        console.log(`[TV] Interfaz ${running} (bundle ${current.bundle.id}, app ${current.native})`)

        const res = await fetch(`${API_URL}/updates/latest.json`, { cache: 'no-store' })
        if (!res.ok) return
        const latest = (await res.json()) as LatestManifest
        if (!latest?.version || !latest?.path || latest.version === running) return

        const { bundles } = await CapacitorUpdater.list()
        let bundle = bundles.find((b) => b.version === latest.version)
        if (!bundle) {
          const url = new URL(latest.path, `${API_URL}/updates/`).toString()
          console.log(`[TV] Descargando actualización ${latest.version}`)
          bundle = await CapacitorUpdater.download({ url, version: latest.version, checksum: latest.checksum })
        }
        if (cancelled) return
        console.log(`[TV] Aplicando actualización ${latest.version}`)
        // Switches to the new bundle and reloads the app (a couple of seconds of black screen).
        await CapacitorUpdater.set({ id: bundle.id })
      } catch (err) {
        console.warn('[TV] Actualización no disponible:', err)
      }
    }

    check()
    const timer = setInterval(check, CHECK_EVERY_MS)
    return () => {
      cancelled = true
      clearInterval(timer)
    }
  }, [])
}
