/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as UsersRouteImport } from './routes/users'
import { Route as UserNewRouteImport } from './routes/user-new'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ScreensRouteImport } from './routes/screens'
import { Route as ScreenAddRouteImport } from './routes/screen-add'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as PlaylistsRouteImport } from './routes/playlists'
import { Route as PlaylistNewRouteImport } from './routes/playlist-new'
import { Route as PlaylistRouteImport } from './routes/playlist'
import { Route as PantallasRouteImport } from './routes/pantallas'
import { Route as NuevaPantallaRouteImport } from './routes/nueva-pantalla'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as EstadoRouteImport } from './routes/estado'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideoEditIdRouteImport } from './routes/video-edit.$id'
import { Route as UserEditIdRouteImport } from './routes/user-edit.$id'
import { Route as ScreenEditIdRouteImport } from './routes/screen-edit.$id'
import { Route as PlaylistViewIdRouteImport } from './routes/playlist-view.$id'
import { Route as PlaylistEditIdRouteImport } from './routes/playlist-edit.$id'
import { Route as EditIdRouteImport } from './routes/edit.$id'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const UserNewRoute = UserNewRouteImport.update({
  id: '/user-new',
  path: '/user-new',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreensRoute = ScreensRouteImport.update({
  id: '/screens',
  path: '/screens',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenAddRoute = ScreenAddRouteImport.update({
  id: '/screen-add',
  path: '/screen-add',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsRoute = PlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistNewRoute = PlaylistNewRouteImport.update({
  id: '/playlist-new',
  path: '/playlist-new',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistRoute = PlaylistRouteImport.update({
  id: '/playlist',
  path: '/playlist',
  getParentRoute: () => rootRouteImport,
} as any)
const PantallasRoute = PantallasRouteImport.update({
  id: '/pantallas',
  path: '/pantallas',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaPantallaRoute = NuevaPantallaRouteImport.update({
  id: '/nueva-pantalla',
  path: '/nueva-pantalla',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadoRoute = EstadoRouteImport.update({
  id: '/estado',
  path: '/estado',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoEditIdRoute = VideoEditIdRouteImport.update({
  id: '/video-edit/$id',
  path: '/video-edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UserEditIdRoute = UserEditIdRouteImport.update({
  id: '/user-edit/$id',
  path: '/user-edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenEditIdRoute = ScreenEditIdRouteImport.update({
  id: '/screen-edit/$id',
  path: '/screen-edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistViewIdRoute = PlaylistViewIdRouteImport.update({
  id: '/playlist-view/$id',
  path: '/playlist-view/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistEditIdRoute = PlaylistEditIdRouteImport.update({
  id: '/playlist-edit/$id',
  path: '/playlist-edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EditIdRoute = EditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/client': typeof ClientRoute
  '/estado': typeof EstadoRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/nueva-pantalla': typeof NuevaPantallaRoute
  '/pantallas': typeof PantallasRoute
  '/playlist': typeof PlaylistRoute
  '/playlist-new': typeof PlaylistNewRoute
  '/playlists': typeof PlaylistsRoute
  '/roles': typeof RolesRoute
  '/screen-add': typeof ScreenAddRoute
  '/screens': typeof ScreensRoute
  '/status': typeof StatusRoute
  '/upload': typeof UploadRoute
  '/user-new': typeof UserNewRoute
  '/users': typeof UsersRoute
  '/videos': typeof VideosRoute
  '/edit/$id': typeof EditIdRoute
  '/playlist-edit/$id': typeof PlaylistEditIdRoute
  '/playlist-view/$id': typeof PlaylistViewIdRoute
  '/screen-edit/$id': typeof ScreenEditIdRoute
  '/user-edit/$id': typeof UserEditIdRoute
  '/video-edit/$id': typeof VideoEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/client': typeof ClientRoute
  '/estado': typeof EstadoRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/nueva-pantalla': typeof NuevaPantallaRoute
  '/pantallas': typeof PantallasRoute
  '/playlist': typeof PlaylistRoute
  '/playlist-new': typeof PlaylistNewRoute
  '/playlists': typeof PlaylistsRoute
  '/roles': typeof RolesRoute
  '/screen-add': typeof ScreenAddRoute
  '/screens': typeof ScreensRoute
  '/status': typeof StatusRoute
  '/upload': typeof UploadRoute
  '/user-new': typeof UserNewRoute
  '/users': typeof UsersRoute
  '/videos': typeof VideosRoute
  '/edit/$id': typeof EditIdRoute
  '/playlist-edit/$id': typeof PlaylistEditIdRoute
  '/playlist-view/$id': typeof PlaylistViewIdRoute
  '/screen-edit/$id': typeof ScreenEditIdRoute
  '/user-edit/$id': typeof UserEditIdRoute
  '/video-edit/$id': typeof VideoEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/client': typeof ClientRoute
  '/estado': typeof EstadoRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/nueva-pantalla': typeof NuevaPantallaRoute
  '/pantallas': typeof PantallasRoute
  '/playlist': typeof PlaylistRoute
  '/playlist-new': typeof PlaylistNewRoute
  '/playlists': typeof PlaylistsRoute
  '/roles': typeof RolesRoute
  '/screen-add': typeof ScreenAddRoute
  '/screens': typeof ScreensRoute
  '/status': typeof StatusRoute
  '/upload': typeof UploadRoute
  '/user-new': typeof UserNewRoute
  '/users': typeof UsersRoute
  '/videos': typeof VideosRoute
  '/edit/$id': typeof EditIdRoute
  '/playlist-edit/$id': typeof PlaylistEditIdRoute
  '/playlist-view/$id': typeof PlaylistViewIdRoute
  '/screen-edit/$id': typeof ScreenEditIdRoute
  '/user-edit/$id': typeof UserEditIdRoute
  '/video-edit/$id': typeof VideoEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes'
    | '/client'
    | '/estado'
    | '/history'
    | '/login'
    | '/nueva-pantalla'
    | '/pantallas'
    | '/playlist'
    | '/playlist-new'
    | '/playlists'
    | '/roles'
    | '/screen-add'
    | '/screens'
    | '/status'
    | '/upload'
    | '/user-new'
    | '/users'
    | '/videos'
    | '/edit/$id'
    | '/playlist-edit/$id'
    | '/playlist-view/$id'
    | '/screen-edit/$id'
    | '/user-edit/$id'
    | '/video-edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajustes'
    | '/client'
    | '/estado'
    | '/history'
    | '/login'
    | '/nueva-pantalla'
    | '/pantallas'
    | '/playlist'
    | '/playlist-new'
    | '/playlists'
    | '/roles'
    | '/screen-add'
    | '/screens'
    | '/status'
    | '/upload'
    | '/user-new'
    | '/users'
    | '/videos'
    | '/edit/$id'
    | '/playlist-edit/$id'
    | '/playlist-view/$id'
    | '/screen-edit/$id'
    | '/user-edit/$id'
    | '/video-edit/$id'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/client'
    | '/estado'
    | '/history'
    | '/login'
    | '/nueva-pantalla'
    | '/pantallas'
    | '/playlist'
    | '/playlist-new'
    | '/playlists'
    | '/roles'
    | '/screen-add'
    | '/screens'
    | '/status'
    | '/upload'
    | '/user-new'
    | '/users'
    | '/videos'
    | '/edit/$id'
    | '/playlist-edit/$id'
    | '/playlist-view/$id'
    | '/screen-edit/$id'
    | '/user-edit/$id'
    | '/video-edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  ClientRoute: typeof ClientRoute
  EstadoRoute: typeof EstadoRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  NuevaPantallaRoute: typeof NuevaPantallaRoute
  PantallasRoute: typeof PantallasRoute
  PlaylistRoute: typeof PlaylistRoute
  PlaylistNewRoute: typeof PlaylistNewRoute
  PlaylistsRoute: typeof PlaylistsRoute
  RolesRoute: typeof RolesRoute
  ScreenAddRoute: typeof ScreenAddRoute
  ScreensRoute: typeof ScreensRoute
  StatusRoute: typeof StatusRoute
  UploadRoute: typeof UploadRoute
  UserNewRoute: typeof UserNewRoute
  UsersRoute: typeof UsersRoute
  VideosRoute: typeof VideosRoute
  EditIdRoute: typeof EditIdRoute
  PlaylistEditIdRoute: typeof PlaylistEditIdRoute
  PlaylistViewIdRoute: typeof PlaylistViewIdRoute
  ScreenEditIdRoute: typeof ScreenEditIdRoute
  UserEditIdRoute: typeof UserEditIdRoute
  VideoEditIdRoute: typeof VideoEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-new': {
      id: '/user-new'
      path: '/user-new'
      fullPath: '/user-new'
      preLoaderRoute: typeof UserNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screens': {
      id: '/screens'
      path: '/screens'
      fullPath: '/screens'
      preLoaderRoute: typeof ScreensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screen-add': {
      id: '/screen-add'
      path: '/screen-add'
      fullPath: '/screen-add'
      preLoaderRoute: typeof ScreenAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist-new': {
      id: '/playlist-new'
      path: '/playlist-new'
      fullPath: '/playlist-new'
      preLoaderRoute: typeof PlaylistNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist': {
      id: '/playlist'
      path: '/playlist'
      fullPath: '/playlist'
      preLoaderRoute: typeof PlaylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pantallas': {
      id: '/pantallas'
      path: '/pantallas'
      fullPath: '/pantallas'
      preLoaderRoute: typeof PantallasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nueva-pantalla': {
      id: '/nueva-pantalla'
      path: '/nueva-pantalla'
      fullPath: '/nueva-pantalla'
      preLoaderRoute: typeof NuevaPantallaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estado': {
      id: '/estado'
      path: '/estado'
      fullPath: '/estado'
      preLoaderRoute: typeof EstadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-edit/$id': {
      id: '/video-edit/$id'
      path: '/video-edit/$id'
      fullPath: '/video-edit/$id'
      preLoaderRoute: typeof VideoEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-edit/$id': {
      id: '/user-edit/$id'
      path: '/user-edit/$id'
      fullPath: '/user-edit/$id'
      preLoaderRoute: typeof UserEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screen-edit/$id': {
      id: '/screen-edit/$id'
      path: '/screen-edit/$id'
      fullPath: '/screen-edit/$id'
      preLoaderRoute: typeof ScreenEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist-view/$id': {
      id: '/playlist-view/$id'
      path: '/playlist-view/$id'
      fullPath: '/playlist-view/$id'
      preLoaderRoute: typeof PlaylistViewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist-edit/$id': {
      id: '/playlist-edit/$id'
      path: '/playlist-edit/$id'
      fullPath: '/playlist-edit/$id'
      preLoaderRoute: typeof PlaylistEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$id': {
      id: '/edit/$id'
      path: '/edit/$id'
      fullPath: '/edit/$id'
      preLoaderRoute: typeof EditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  ClientRoute: ClientRoute,
  EstadoRoute: EstadoRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  NuevaPantallaRoute: NuevaPantallaRoute,
  PantallasRoute: PantallasRoute,
  PlaylistRoute: PlaylistRoute,
  PlaylistNewRoute: PlaylistNewRoute,
  PlaylistsRoute: PlaylistsRoute,
  RolesRoute: RolesRoute,
  ScreenAddRoute: ScreenAddRoute,
  ScreensRoute: ScreensRoute,
  StatusRoute: StatusRoute,
  UploadRoute: UploadRoute,
  UserNewRoute: UserNewRoute,
  UsersRoute: UsersRoute,
  VideosRoute: VideosRoute,
  EditIdRoute: EditIdRoute,
  PlaylistEditIdRoute: PlaylistEditIdRoute,
  PlaylistViewIdRoute: PlaylistViewIdRoute,
  ScreenEditIdRoute: ScreenEditIdRoute,
  UserEditIdRoute: UserEditIdRoute,
  VideoEditIdRoute: VideoEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
